name: CI
on:
  push:
jobs:
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
+     - uses: olafurpg/setup-scala@v11
      - run: sbt compile
      - run: sbt publish