name: CI
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v11
      - name: Compile
        run: sbt compile
      - name: Publish
        run: sbt publish